export const ACCESS_TOKEN_KEY = "access_token";
export const REFRESH_TOKEN_KEY = "refresh_token";
export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_TOKEN_REFRESHED = "AUTH_TOKEN_REFRESHED";

export const FEED_FETCH_REQUEST          = 'FEED_FETCH_REQUEST';
export const FEED_FETCH_SUCCESS          = 'FEED_FETCH_SUCCESS';
export const FEED_FETCH_FAILURE          = 'FEED_FETCH_FAILURE';
export const FEED_SET_FILTER             = 'FEED_SET_FILTER';
export const FEED_APPEND_RECOMMENDATIONS = 'FEED_APPEND_RECOMMENDATIONS';
export const FEED_PROFILE_REQUEST        = 'FEED_PROFILE_REQUEST';
export const FEED_PROFILE_SUCCESS        = 'FEED_PROFILE_SUCCESS';
export const FEED_PROFILE_FAILURE        = 'FEED_PROFILE_FAILURE';
